Add toolbar section of desktop verstion
sajjadrajaee/Sajjad-Portfolio pull request #4
Opened 2022-04-29 07:07 UTC by sajjadrajaee

Add toolbar, About me, and the first section of the portfolio.

2022-04-29 07:26 UTC, Chrissiku reviewed
Hello @sajjadrajaee , Good job so far,

please, check my comment bellow to ajust some of your code.

### General Requerement ♻️ 
- [ ] Try to use HTML & CSS best practive
- [ ] Avoid linters errors before you submit

Thank You 🤝

2022-04-29 07:26 UTC, Chrissiku commented on index.html
> -        <nav>
Kindly put the logo of your project inside an anchor (<a>) tag, so that it will be cliquable.

2022-04-29 07:26 UTC, Chrissiku commented on index.html
> +    </nav>
- [ ] Kindly put menu links inside an anchor tag, because they are clickable items (links).

2022-04-29 07:26 UTC, Chrissiku commented on style.css
> +@media screen and (max-width:768px) {
- [ ] You don't have to add the screen size for mobile devices as you are working with mobile first approach, kindly try to just remove the @media for this maximun size of screen

2022-04-29 07:28 UTC, NatiDeme reviewed
# Good pointers
- The UI renders as it was presented in the design
- Clean and readable code
-
# Changes required
- Kindly make sure to fix all the linter errors
- Please go through inline comments from the morning session team

2022-04-29 07:28 UTC, NatiDeme commented on index.html
> +            <a href="#">
- [ ] Kindly don't forget to add a link to your social as this `a` currently takes you back to the home page.

2022-04-30 04:19 UTC, mahbubul14 requested changes
Hi @sajjadrajaee ,

Good job so far! :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

# Required Changes ♻️

- [ ] Please check the inline comments under the review. :arrow_down: 

###  To Highlights
:heavy_check_mark: No linters error.
:heavy_check_mark: Github flow used properly.
:heavy_check_mark: Descriptive PR title & description.

### Optional suggestions

- [ ] In your `README` file, You need to update the "Getting Started" section. This should be an example of how you may give instructions on setting up your project locally.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also reach me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-04-30 04:19 UTC, mahbubul14 commented on index.html
> +    <h2 id="logo">Sajjad</h2>
- [ ] Kindly wrap this `h2` tag with the `a` tag. I think the logo should be clickable. :+1:

2022-04-30 04:19 UTC, mahbubul14 commented on index.html
> +          <div id="primary-text">I’m Sajjad Glad<br /> to see you!</div>
- [ ] I think you should use the `h1` tag instead of the `div` tag here.  The main title of the page should be in a `h1` tag. Please fix it. :+1:

2022-04-30 04:19 UTC, mahbubul14 commented on index.html
> +          </div>
- [ ] Kindly use the `p` tag instead of the `div` tag here. :+1:

2022-04-30 04:19 UTC, mahbubul14 commented on index.html
>            </div>
- [ ] The list of social media icons should use the `ul` tag to group them and `li` for per icon.

Here is an example:

```
<ul>
  <li>
    <a href="https://twitter.com/sajjadrajaee"> <img src="images/social/twitter.svg" alt="social icons" /> </a>
  <li>
<ul>

```

2022-04-30 19:30 UTC, danielufeli requested changes
Hi sajjadrajaee, 

## Great work on making the changes requested by a previous reviewer 👏 👏 👏
You've done well implementing most of the requested changes, but there are still some which aren't addressed yet.

[](https://user-images.githubusercontent.com/44057863/166109715-8bbd7898-5758-40b9-b328-e2ed2cb38167.gif)

## Highlights
✔️ Splendid UI Design
✔️ Meaningful commit messages used
✔️ Good use of Github flow

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @danielufeli in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-30 19:30 UTC, danielufeli commented on index.html
> +        <li>Portfolio</li>
- [ ] Nice working on your header, kindly link the menu using `a` tag just like the previous reviewer requested.

2022-04-30 20:12 UTC, danielufeli approved these changes
Hi @sajjadrajaee, 

Great work on making the changes requested by a previous reviewer,
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![a](https://camo.githubusercontent.com/40c24648ada128030359495b9504e95985194c3f4bbeabf0485e740ecd253bcc/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6a4a5143327075565a70544d4f34765573302f67697068792e676966)

## Highlights
- Nice commits messages✔️
- Descriptive PR ✔️
- Clean Design ✔️
- Good use of Github flow ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @danielufeli in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-30 20:18 UTC, merged